'use client';

import { motion } from 'framer-motion';
import {
    BrainCircuit,
    Trophy,
    BarChart3,
    Timer,
    Shield,
    Layers,
} from 'lucide-react';

const FEATURES = [
    {
        icon: BrainCircuit,
        color: '#6366f1',
        title: 'AI Question Engine',
        description:
            'OpenAI 5.3 powered LLM generates infinite unique questions. No two quizzes are the same - ever.',
    },
    {
        icon: Timer,
        color: '#06b6d4',
        title: 'Timed Practice',
        description:
            'Simulate real interview pressure with countdown timers and instant grading.',
    },
    {
        icon: BarChart3,
        color: '#10b981',
        title: 'Skill Analytics',
        description:
            'See your accuracy per skill — SQL, Excel, Python, Power BI — and track improvement over time.',
    },
    {
        icon: Trophy,
        color: '#f59e0b',
        title: 'Leaderboard',
        description:
            'Anonymous peer ranking shows where you stand. Compete without pressure.',
    },
    {
        icon: Layers,
        color: '#ec4899',
        title: 'Persona Quizzes',
        description:
            'Customized for Career Switchers, Job Hoppers, and Freshers — different strategies, different questions.',
    },
    {
        icon: Shield,
        color: '#8b5cf6',
        title: 'AI Performance Report',
        description:
            'After each quiz, get a personalized improvement roadmap generated by AI based on your wrong answers.',
    },
];

export default function FeaturesGrid() {
    return (
        <section
            id="how-it-works"
            style={{
                padding: '80px 20px',
                maxWidth: '1200px',
                margin: '0 auto',
            }}
        >
            <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                style={{ textAlign: 'center', marginBottom: '3.5rem' }}
            >
                <h2
                    style={{
                        fontSize: '2.5rem',
                        fontWeight: '800',
                        marginBottom: '0.75rem',
                    }}
                >
                    Everything You Need to{' '}
                    <span className="text-gradient">Ace the Interview</span>
                </h2>
                <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem', maxWidth: '600px', margin: '0 auto' }}>
                    Built by mentors who've helped 500+ analysts land jobs at top companies
                </p>
            </motion.div>

            <div
                style={{
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
                    gap: '1.5rem',
                }}
            >
                {FEATURES.map((f, i) => {
                    const Icon = f.icon;
                    return (
                        <motion.div
                            key={f.title}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.08 }}
                            whileHover={{ y: -5 }}
                            className="glass-card"
                            style={{ padding: '2rem', display: 'flex', gap: '1.25rem' }}
                        >
                            <div
                                style={{
                                    width: '52px',
                                    height: '52px',
                                    borderRadius: '14px',
                                    background: `${f.color}12`,
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    flexShrink: 0,
                                }}
                            >
                                <Icon size={26} color={f.color} />
                            </div>
                            <div>
                                <h3
                                    style={{
                                        fontSize: '1.15rem',
                                        fontWeight: '700',
                                        marginBottom: '0.4rem',
                                    }}
                                >
                                    {f.title}
                                </h3>
                                <p
                                    style={{
                                        color: 'var(--text-secondary)',
                                        fontSize: '0.9rem',
                                        lineHeight: '1.5',
                                    }}
                                >
                                    {f.description}
                                </p>
                            </div>
                        </motion.div>
                    );
                })}
            </div>
        </section>
    );
}
