'use client';

import { motion } from 'framer-motion';
import { ArrowRight, Play, LayoutDashboard } from 'lucide-react';
import Link from 'next/link';

interface HeroSectionProps {
    isLoggedIn?: boolean;
    isLoading?: boolean;
}

export default function HeroSection({ isLoggedIn = false, isLoading = false }: HeroSectionProps) {
    return (
        <section
            style={{
                padding: '80px 20px 60px',
                textAlign: 'center',
                maxWidth: '1000px',
                margin: '0 auto',
                position: 'relative',
            }}
        >
            {/* Floating pill badge */}
            <motion.div
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '8px',
                    padding: '6px 18px',
                    borderRadius: '24px',
                    background: 'rgba(99, 102, 241, 0.1)',
                    border: '1px solid rgba(99, 102, 241, 0.2)',
                    fontSize: '0.85rem',
                    color: 'var(--text-accent)',
                    marginBottom: '2rem',
                }}
            >
                <span
                    style={{
                        width: '8px',
                        height: '8px',
                        borderRadius: '50%',
                        background: '#10b981',
                        boxShadow: '0 0 6px #10b981',
                    }}
                />
                Trusted by 500+ Data Analysts
            </motion.div>

            <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                style={{
                    fontSize: 'clamp(2.5rem, 5vw, 4.5rem)',
                    fontWeight: '800',
                    marginBottom: '1.5rem',
                    lineHeight: '1.08',
                    letterSpacing: '-0.02em',
                }}
            >
                Crack Your Data Analyst
                <br />
                Interview with{' '}
                <span className="text-gradient">AI-Powered Practice</span>
            </motion.h1>

            <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.35 }}
                style={{
                    fontSize: '1.2rem',
                    color: 'var(--text-secondary)',
                    marginBottom: '2.5rem',
                    maxWidth: '680px',
                    margin: '0 auto 2.5rem',
                    lineHeight: '1.6',
                }}
            >
                Personalized quizzes for SQL, Excel, Python & Power BI — generated by
                AI, graded instantly, with deep performance insights. Built by mentors,
                for aspiring analysts.
            </motion.p>

            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.5 }}
                style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap', minHeight: '56px' }}
            >
                {isLoading ? (
                    <div style={{ padding: '16px 36px', height: '56px', borderRadius: '8px', background: 'rgba(99,102,241,0.1)', minWidth: '180px' }} />
                ) : isLoggedIn ? (
                    <Link
                        href="/dashboard"
                        className="btn-primary"
                        style={{
                            fontSize: '1.1rem',
                            padding: '16px 36px',
                            textDecoration: 'none',
                        }}
                    >
                        Go to Dashboard <LayoutDashboard size={20} />
                    </Link>
                ) : (
                    <Link
                        href="/get-started"
                        className="btn-primary"
                        style={{
                            fontSize: '1.1rem',
                            padding: '16px 36px',
                            textDecoration: 'none',
                        }}
                    >
                        Start Free Quiz <ArrowRight size={20} />
                    </Link>
                )}
                <Link
                    href="#how-it-works"
                    style={{
                        padding: '16px 36px',
                        borderRadius: '8px',
                        border: '1px solid var(--border-color)',
                        color: 'var(--text-primary)',
                        textDecoration: 'none',
                        fontWeight: '600',
                        background: 'var(--subtle-bg)',
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                    }}
                >
                    <Play size={18} fill="var(--text-accent)" color="var(--text-accent)" /> See How It Works
                </Link>
            </motion.div>

            {/* Stats strip */}
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.7 }}
                style={{
                    display: 'flex',
                    justifyContent: 'center',
                    gap: '3rem',
                    marginTop: '4rem',
                    flexWrap: 'wrap',
                }}
            >
                {[
                    { value: '10K+', label: 'Questions Generated' },
                    { value: '92%', label: 'Accuracy Improvement' },
                    { value: '4.8★', label: 'User Rating' },
                ].map((stat, i) => (
                    <div key={i}>
                        <div style={{ fontSize: '1.75rem', fontWeight: '800' }}>{stat.value}</div>
                        <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>{stat.label}</div>
                    </div>
                ))}
            </motion.div>
        </section>
    );
}
